### ISSUE TITLE
Some info about this engine

### ISSUE THREAD

**Issue by Cosetto** [ZQF-ReVN/RxGSD#1]
First of fall, thanks for making this tool, this is such a coincidence since I'm looking for this engine's tools.
As for the infos:
_ We can extract .gsp archive with GARbro and arc_conv. Arc_conv supports archive creation of this engine with command: arc_conv.exe --pack gsp in_folder out_gsp
_ For .bmz, GARbro to convert from and to .bmz with GARbro
![image](https://github.com/Dir-A/GSDTools/assets/81801486/f441b629-9a81-465f-a737-71fb3c8a3e6f)
Is there a better command for line for SPT tool?

**Comment by Dir-A** [comment]
Actually, I don't even know them.
But I think I'm almost done.

The structure of a gsp pack is simple enough that it can be easily repack, but no one wants to release an entire pack as a patch,So So I hooked the engine's virtual filesystem to read the individual files.

bmz is actually a fully structured bmp image with zlib compression, but through reverse analysis of the engine, I found that the engine can actually read bmp images directly, you just need to convert bmz to bmp and then change the file extension to bmz (if you don't care about the file size)
The reasoning is that the engine will determine if the first four bytes are 'ZLC3' to decompress them

The spt script garbro will not decrypt, but crass will, but I have not used crass, through my analysis of the spt file decryption, I found that it has two times to decrypt, respectively, need to use the two bytes at the beginning of the file, that is, each byte control a decryption condition.
For the first decryption, there are three modes, controlled by the second byte of the file, but this byte is encrypted need xor 0xF0, this byte can only be 0-2 otherwise not decrypted.
For the second decryption, it is controlled by the first byte, which is not decrypted if it is greater than or equal to 8.
So all you need to do is decrypt the spt file and change the first two bytes to 0xFF and the game will read it normally without encrypting it back.

I'm doing some research on text importing for spt these days, and I've noticed that spt files seem to be some sort of data structure that is read by chunks.

I've actually written out tools to export spt text to json and import it back, just haven't perfected it yet.The principle is to insert text directly, after testing no problems have been found.
https://github.com/Dir-A/GSDTools/blob/main/src/SPT_Decoder/main.cpp#L53
https://github.com/Dir-A/GSDTools/blob/main/src/SPT_Decoder/main.cpp#L244

**Comment by Cosetto** [comment]
Can you test with [this game](https://vndb.org/v5160)? When I tried to insert the text, the tool didn't throw any exception, but it didn't create new file either.

**Comment by Cosetto** [comment]
Okay, I figured it out. It looks like "0x00" byte is something that present the furigana, but the tool doesn't work when it's there.
![image](https://github.com/Dir-A/GSDTools/assets/81801486/a2282d1a-51da-4819-8803-8a5df720b42d)
Also, the game still runs after packing without compressing:
![image](https://github.com/Dir-A/GSDTools/assets/81801486/c9b6bc29-73c5-4394-9103-66a6acf25479)

**Comment by Cosetto** [comment]
For reference, the font size is in init_text.spt and set before font's name like this:
![image](https://github.com/Dir-A/GSDTools/assets/81801486/f2f941e4-2c75-4792-8a2e-2fd756f4ec33)
![image](https://github.com/Dir-A/GSDTools/assets/81801486/27dd21a5-866e-4a48-9ec1-3a1b2fda941b)

**Comment by Cosetto** [comment]
![image](https://github.com/Dir-A/GSDTools/assets/81801486/56eae2ff-a37d-44d3-b8d4-a98006a0df95)
Is this the correct code to batch insert the script? I'm confused

**Comment by Dir-A** [comment]
Don't use it, it has serious bugs, I'm writing a new tool

**Comment by Cosetto** [comment]
Got it

**Comment by Cosetto** [comment]
I got this error when coming to this script:
> Processing file: input_script\scene_s0727a.spt
> Unknow Char Type!

[scene_s0727a.zip](https://github.com/Dir-A/GSDTools/files/13711370/scene_s0727a.zip)

**Comment by Dir-A** [comment]
Use the latest commit code

**Comment by Cosetto** [comment]
![image](https://github.com/Dir-A/GSDTools/assets/81801486/eb7f34da-1dbd-4269-b150-21ca4284eb3a)

**Comment by Dir-A** [comment]
0x5 is to control the text color, does not affect the normal import
I haven't had time to write the import code for the control character.

**Comment by Cosetto** [comment]
Oh, okay

**Comment by Cosetto** [comment]
Another bug I found.
So there are Sys_title.bmz and Sys_title_start.bmz, if I edit them, the button in-game will literally freeze.

![Sys_title](https://github.com/Dir-A/GSDTools/assets/81801486/ea4b096d-7469-4599-a02b-fe2c928f5148)
![Sys_title_start](https://github.com/Dir-A/GSDTools/assets/81801486/11e921b7-dd01-475e-815b-2bde50a1bfe7)

I don't know if my edit skill is bad or there's a file control the images?

**Comment by Dir-A** [comment]
try the latest commit

**Comment by Cosetto** [comment]
Thanks bro, it works when we create new Image.gsp, while the VFS hook still freezes

**Comment by Dir-A** [comment]
try 3a053caa16fdbe5f5947e6096b32035e70ea6ec1

**Comment by Cosetto** [comment]
Thanks again, it works like a charm now!

**Comment by Cosetto** [comment]
Bro, can you also add support for the files contain names info?
![image](https://github.com/Dir-A/GSDTools/assets/81801486/5953c3e6-71e9-4f59-b4da-7497ce929f14)
We can edit Globat.dat with hex editor, but in **bl_windup.spt** and **color_font.spt**, the Romanize names are too long to fit in and likely overwrite 0x11 byte (idk what is it but game crashed if we touch it), e.g: 新一 as Shin'ichi, 正義 as Masayoshi. And the names must be in that offset to display its color in-game correctly, so I can't make use of the 00 bytes behind the names.
![image](https://github.com/Dir-A/GSDTools/assets/81801486/63223256-1552-4465-89ed-aecec98e198d)
Aside from that, do you know how to disable the full-width rendering on ASCII characters?
![image](https://github.com/Dir-A/GSDTools/assets/81801486/1c080f13-c895-4228-925e-0e1ee85492db)

**Comment by Dir-A** [comment]
Now you can use spt_parser to convert spt to json and modify contents of json and then convert json back to spt, thatmeans you can edit the spt via json.
I haven't tested the code carefully yet, just experimenting at the moment.

The submodules has been added to the project, make sure that when you clone the project you also clone the submodule.
